name: Publish to crates.io

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - id: get_version
      name: Get version
      uses: battila7/get-version-action@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    # TODO: figure out if we need caching
    - uses: Swatinem/rust-cache@v1

    - name: Bump crate version
      uses: thomaseizinger/set-crate-version@master
      with:
        version: ${{ steps.get_version.outputs.version-without-v }}

    - name: Publish crate
      uses: katyo/publish-crates@v1
      with:
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
